### ISSUE TITLE
Declaração do Contrato da API

### ISSUE THREAD

**Issue by DavviSantos** [marcelofiddelis/projeto-eventos#17]
Definir e documentar o contrato da API, que inclui os endpoints, métodos HTTP, parâmetros de entrada e saída, códigos de resposta HTTP, e possíveis erros. A API deve seguir padrões RESTful e ser consistente para facilitar o consumo por outras aplicações ou clientes.

**Comment by marcelofiddelis** [comment]
Resolvida a implementação
